import type { MotionZone } from "../types";

interface Camera {
  id: string;
  name: string;
  stream_url: string;
  stream_type: string;
  snapshot_url: string | null;
  location_label: string | null;
  username: string | null;
  auth_token: string | null;
  snapshot_interval: number;
  motion_sensitivity: number;
  recording_enabled: boolean;
  recording_mode: string;
  recording_trigger_objects: string[] | null;
  recording_clip_pre: number;
  recording_clip_post: number;
  vlm_provider_id: string | null;
  vlm_prompt: string | null;
  vlm_interval: number;
  vlm_max_tokens: number;
  vlm_max_input_tokens: number | null;
  vlm_refiner_provider_id: string | null;
  vlm_refiner_trigger_objects: string[] | null;
  vlm_refiner_keywords: string[] | null;
  vlm_refiner_max_tokens: number | null;
  vlm_refiner_max_input_tokens: number | null;
  detect_objects: boolean;
  detect_faces: boolean;
  detect_plates: boolean;
  detect_classes: string[] | null;
  scene_mode: string;
  plateless_reid_enabled: boolean | null;
  object_confidence: number;
  vlm_trigger: string;
  vlm_trigger_objects: string[] | null;
  digest_enabled: boolean;
  digest_period: string;
  digest_provider_id: string | null;
  digest_prompt: string | null;
  retention_mode: string;
  retention_days: number;
  retention_gb: number;
  detection_models: {model: string; confidence: number; enabled: boolean; label_filter: string[]}[] | null;
  detection_merge: string;
  detection_consensus_min: number;
  summary_provider_id: string | null;
  summary_mode: string;
  summary_period_seconds: number;
  summary_event_quiet_seconds: number;
  summary_event_trigger_objects: string[] | null;
  summary_event_min_duration_seconds: number;
  summary_max_tokens: number;
  conversation_gap_seconds: number;
  conversation_summary_enabled: boolean;
  conversation_min_messages_for_summary: number;
  incident_tracking_enabled: boolean;
  incident_idle_seconds: number;
  privacy_zone_targets: string[] | null;
  privacy_zone_blur_strength: number;
  timezone: string | null;
  ptz_smart_track_enabled: boolean;
  ptz_smart_track_targets: string[] | null;
  ptz_smart_track_ignore: string[] | null;
  ptz_smart_track_priority: string[] | null;
  ptz_smart_track_lost_seconds: number;
  ptz_smart_track_home_preset: string | null;
  ptz_smart_track_zoom: boolean;
  ptz_smart_track_deadzone: number;
  ptz_smart_track_max_speed: number;
  ptz_smart_track_gain: number;
  ptz_smart_track_min_confidence: number;
  ptz_smart_track_move_budget_per_minute: number;
  ptz_profile_token: string;
  motion_zones: MotionZone[] | null;
  status: string;
  status_reason?: string | null;
  next_retry_at?: number | null;
  retry_delay_seconds?: number | null;
  width: number | null;
  height: number | null;
  fps: number | null;
  created_at: string;
  updated_at: string;
}

interface Provider {
  id: string;
  name: string;
  kind: string;
  base_url: string;
  default_model: string | null;
  active: boolean;
}

export { type Camera, type Provider };
