"""add camera stream_type and auth fields

Revision ID: 649eff7090a9
Revises: 0cac19a54293
Create Date: 2026-04-16 13:07:43.725255
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '649eff7090a9'
down_revision: Union[str, None] = '0cac19a54293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with server_default so existing rows get values
    op.add_column('cameras', sa.Column('stream_type', sa.String(length=32), nullable=False, server_default='rtsp'))
    op.add_column('cameras', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('cameras', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('cameras', sa.Column('auth_token', sa.String(length=512), nullable=True))
    op.add_column('cameras', sa.Column('snapshot_interval', sa.Float(), nullable=False, server_default='2.0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'snapshot_interval')
    op.drop_column('cameras', 'auth_token')
    op.drop_column('cameras', 'password')
    op.drop_column('cameras', 'username')
    op.drop_column('cameras', 'stream_type')
    # ### end Alembic commands ###
