"""add camera retention policy

Revision ID: 814d1f1227a9
Revises: d5945a3420c8
Create Date: 2026-04-16 13:25:26.872272
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '814d1f1227a9'
down_revision: Union[str, None] = 'd5945a3420c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('retention_mode', sa.String(length=16), nullable=False, server_default='none'))
    op.add_column('cameras', sa.Column('retention_days', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('cameras', sa.Column('retention_gb', sa.Float(), nullable=False, server_default='50.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'retention_gb')
    op.drop_column('cameras', 'retention_days')
    op.drop_column('cameras', 'retention_mode')
    # ### end Alembic commands ###
