"""add camera status log table

Revision ID: 936b67ae5404
Revises: 814d1f1227a9
Create Date: 2026-04-16 13:33:20.920668
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '936b67ae5404'
down_revision: Union[str, None] = '814d1f1227a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_status_logs_camera_id'), 'camera_status_logs', ['camera_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camera_status_logs_camera_id'), table_name='camera_status_logs')
    op.drop_table('camera_status_logs')
    # ### end Alembic commands ###
