"""add per-camera digest config

Revision ID: d49e5aa857bd
Revises: 936b67ae5404
Create Date: 2026-04-16 13:43:48.810651
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'd49e5aa857bd'
down_revision: Union[str, None] = '936b67ae5404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('digest_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('cameras', sa.Column('digest_period', sa.String(length=16), nullable=False, server_default='24h'))
    op.add_column('cameras', sa.Column('digest_provider_id', sa.UUID(), nullable=True))
    op.add_column('cameras', sa.Column('digest_prompt', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'cameras', 'providers', ['digest_provider_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_column('cameras', 'digest_prompt')
    op.drop_column('cameras', 'digest_provider_id')
    op.drop_column('cameras', 'digest_period')
    op.drop_column('cameras', 'digest_enabled')
    # ### end Alembic commands ###
