"""add per-camera perception config

Revision ID: d5945a3420c8
Revises: 649eff7090a9
Create Date: 2026-04-16 13:15:51.684502
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'd5945a3420c8'
down_revision: Union[str, None] = '649eff7090a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('vlm_provider_id', sa.UUID(), nullable=True))
    op.add_column('cameras', sa.Column('vlm_prompt', sa.Text(), nullable=True))
    op.add_column('cameras', sa.Column('vlm_interval', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('cameras', sa.Column('vlm_max_tokens', sa.Integer(), nullable=False, server_default='200'))
    op.add_column('cameras', sa.Column('detect_objects', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('cameras', sa.Column('detect_faces', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('cameras', sa.Column('object_confidence', sa.Float(), nullable=False, server_default='0.35'))
    op.create_foreign_key(None, 'cameras', 'providers', ['vlm_provider_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_column('cameras', 'object_confidence')
    op.drop_column('cameras', 'detect_faces')
    op.drop_column('cameras', 'detect_objects')
    op.drop_column('cameras', 'vlm_max_tokens')
    op.drop_column('cameras', 'vlm_interval')
    op.drop_column('cameras', 'vlm_prompt')
    op.drop_column('cameras', 'vlm_provider_id')
    # ### end Alembic commands ###
